from __future__ import annotations

import shutil
import subprocess
import tempfile
import unittest
from importlib.resources import files
from pathlib import Path

from should_i_jev.code_scan import scan_code
from should_i_jev.jev_client import ask_choice
from should_i_jev.migrate import apply_patch, generate as generate_migration
from should_i_jev.selfcheck import run_selfcheck

FIXTURES = Path(str(files("should_i_jev").joinpath("fixtures")))
SAMPLE = FIXTURES / "sample_code"

GIT = shutil.which("git")


class MigrateTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.scan = scan_code(SAMPLE)

    def test_generate(self):
        with tempfile.TemporaryDirectory() as td:
            out = generate_migration(self.scan, Path(td), min_score=0.60)
            names = {f.name for f in out.files}
            self.assertEqual(names, {"jev_maps.py", "MIGRATION.md", "migration.patch"})
            self.assertEqual(out.sites, 3)          # score >= 0.60 in the sample
            self.assertGreaterEqual(out.maps_n, 1)

            maps_py = (Path(td) / "jev_maps.py").read_text(encoding="utf-8")
            self.assertIn("AUTO-GENERATED by should-i-jev", maps_py)
            self.assertIn("(Choice)", maps_py)
            # unique class names
            classes = [l for l in maps_py.splitlines() if l.startswith("class ")]
            self.assertEqual(len(classes), len(set(classes)))

            patch = (Path(td) / "migration.patch").read_text(encoding="utf-8")
            self.assertIn("TODO(jev-migrate)", patch)
            self.assertIn("+++ b/jev_maps.py", patch)
            self.assertIn("--- /dev/null", patch)
            self.assertNotIn("content_gen.py", patch.replace("jev-migration", ""))  # not decision-shaped

    def test_min_score_cut(self):
        with tempfile.TemporaryDirectory() as td:
            out = generate_migration(self.scan, Path(td), min_score=0.5)
            self.assertEqual(out.sites, 4)          # includes the 0.56 'maybe' escalation
            patch = (Path(td) / "migration.patch").read_text(encoding="utf-8")
            self.assertIn("email_policies.py", patch)

    @unittest.skipUnless(GIT, "git not available")
    def test_patch_applies_cleanly(self):
        with tempfile.TemporaryDirectory() as td:
            repo = Path(td) / "code"
            shutil.copytree(SAMPLE, repo)
            subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
            out = generate_migration(self.scan, Path(td) / "out")
            ok, err = apply_patch(out.patch, repo)
            self.assertTrue(ok, err)
            marked = (repo / "email_policies.py").read_text(encoding="utf-8")
            self.assertIn("TODO(jev-migrate)", marked)
            self.assertTrue((repo / "jev_maps.py").is_file())
            # applying twice must fail cleanly (already applied)
            ok2, _ = apply_patch(out.patch, repo)
            self.assertFalse(ok2)


class SelfcheckTests(unittest.TestCase):
    def test_mock_over_scan(self):
        scan = scan_code(SAMPLE)
        result = run_selfcheck(scan=scan, limit=10)
        self.assertEqual(result.n, 6)
        self.assertTrue(result.mock)
        self.assertEqual(result.errors, 0)
        # mock mirrors the score: high score -> yes
        yes_rows = [r for r in result.rows if r.choice == "yes"]
        self.assertEqual(len(yes_rows), 4)          # 3 likely + 1 maybe
        for r in result.rows:
            self.assertEqual(r.agrees, (r.choice == "yes") == (r.heuristic in ("likely", "maybe")))

    def test_agreement_definition(self):
        scan = scan_code(SAMPLE)
        result = run_selfcheck(scan=scan)
        expected = sum(
            1 for f in scan.findings
            if ((f.detail.score >= 0.5) == (f.detail.verdict in ("likely", "maybe")))
        ) / len(scan.findings)
        self.assertAlmostEqual(result.agreement, expected)


class JevClientTests(unittest.TestCase):
    def test_mock_default_when_no_url(self):
        answer = ask_choice("q?", ["yes", "no"], state={"score": 0.9}, base_url=None)
        self.assertEqual(answer["choice"], "yes")
        self.assertTrue(answer["mock"])

    def test_mock_low_score_says_no(self):
        answer = ask_choice("q?", ["yes", "no"], state={"score": 0.1}, base_url="mock://offline")
        self.assertEqual(answer["choice"], "no")
        self.assertGreater(answer["p"], 0.5)

    def test_real_bad_url_raises_jev_error(self):
        from should_i_jev.jev_client import JevError

        with self.assertRaises(JevError):
            ask_choice("q?", ["yes", "no"], state={}, base_url="http://127.0.0.1:1/", timeout=1)


if __name__ == "__main__":
    unittest.main()
