"""Generate a reviewable migration changeset for decision-shaped call sites.

Output (under ``--out-dir``, default ``jev-migration/``):

* ``jev_maps.py`` — auto-generated typed-question sketches (Choice/Score) for
  every decision cluster found in the scanned code;
* ``MIGRATION.md`` — per-site guide with before/after sketches;
* ``migration.patch`` — a unified diff that adds ``jev_maps.py`` and inserts a
  ``TODO(jev-migrate)`` marker above each decision-shaped call site.

``--apply`` runs ``git apply`` (works inside or outside a git repo) and prints
the exact branch/PR commands. The patch never deletes or rewrites code — it
marks sites and provides the maps, so the migration PR stays reviewable.
"""
from __future__ import annotations

import difflib
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple

from .code_scan import CodeFinding, CodeScan
from .maps import MapItem, build_maps


@dataclass
class MigrationOutput:
    out_dir: Path
    files: List[Path] = field(default_factory=list)
    patch: Path = None  # type: ignore[assignment]
    sites: int = 0
    maps_n: int = 0


def _class_header(m, index: int) -> str:
    return f"class {m.class_name or 'Map' + str(index)}({m.kind}):"


def _maps_py_source(maps, root_label: str) -> str:
    lines = [
        '"""JEV map sketches — AUTO-GENERATED by should-i-jev.',
        "",
        f"Distilled from decision-shaped LLM call sites found in `{root_label}`.",
        "Sketches are illustrative: adapt names, options and question phrasing,",
        "then wire them to the real Jev SDK / API before shipping.",
        '"""',
        "",
        "# from jev import Choice, Score  # illustrative import — adjust to your SDK",
        "",
    ]
    for i, m in enumerate(maps, start=1):
        lines.append(_class_header(m, i))
        origin = m.origins[0] if m.origins else "?"
        lines.append(f'    """{m.calls} call(s) · score {m.score_range[0]:.2f}–{m.score_range[1]:.2f} · e.g. {origin}"""')
        example = (m.example or "").replace("\\", "\\\\").replace('"""', "'")
        if len(example) > 100:
            example = example[:99] + "…"
        lines.append(f"    question = \"\"\"{example}\"\"\"")
        if m.kind == "Score" and m.options:
            lines.append(f"    range = ({m.options[0]:g}, {m.options[1]:g})  # observed min/max")
        elif m.options:
            opts = ", ".join(f'"{o}"' for o in m.options)
            lines.append(f"    options = ({opts})")
        elif m.note:
            lines.append(f"    # {m.note}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _migration_md(scan: CodeScan, maps, out_dir: Path, min_score: float, applied: bool) -> str:
    sites = [f for f in scan.findings if f.detail.score >= min_score]
    lines: List[str] = []
    add = lines.append
    add("# JEV migration guide")
    add("")
    add(f"_Auto-generated by should-i-jev from a scan of `{scan.root}`._")
    add("")
    add(
        f"{scan.files_scanned} file(s) scanned → {len(scan.findings)} LLM call site(s) → "
        f"**{len(sites)} decision-shaped** (score ≥ {min_score:.2f}) → {len(maps)} Jev map sketch(es)."
    )
    add("")
    add("## Decision-shaped call sites")
    add("")
    add("| Location | Score | Verdict | Handling | Map |")
    add("|---|---:|---|---|---|")
    for f in sites:
        add(
            f"| `{f.path}:{f.line}` | {f.detail.score:.2f} | {f.detail.verdict} | "
            f"{', '.join(f.handling) or '—'} | see below |"
        )
    add("")
    add("## Jev maps")
    add("")
    add("Full sketches live in `jev_maps.py` (created by the patch). Summary:")
    add("")
    add("| Map | Kind | Calls | Score | Example origin |")
    add("|---|---|---:|---|---|")
    for m in maps:
        add(
            f"| `{m.class_name or m.role}` | {m.kind} | {m.calls} | "
            f"{m.score_range[0]:.2f}–{m.score_range[1]:.2f} | `{m.origins[0] if m.origins else '?'}` |"
        )
    add("")
    add("## How to use this")
    add("")
    if applied:
        add("1. The patch has been applied to your working tree — review the diff.")
    else:
        add("1. Apply the patch: `git apply jev-migration/migration.patch` "
            "(or re-run with `--apply`).")
    add("2. Implement each map against the real Jev SDK (sketches are illustrative).")
    add("3. Replace each marked call site with the typed question call.")
    add("4. Shadow-run Jev against live traffic and compare with the calibration harness "
        "(`should-i-jev calibrate`) before cutting over.")
    add("")
    add("## Open the PR")
    add("")
    add("```bash")
    add("git checkout -b jev-migration")
    add("git add -A")
    add('git commit -m "Mark decision-shaped LLM call sites and add Jev map sketches"')
    add("git push -u origin jev-migration")
    add('gh pr create --title "jev-migration: mark decision-shaped call sites" \\')
    add('  --body-file jev-migration/MIGRATION.md')
    add("```")
    add("")
    return "\n".join(lines)


def _patch_for_file(path: Path, rel: str, findings: List[CodeFinding], min_score: float) -> str:
    original = path.read_text(encoding="utf-8").splitlines()
    comment = "#" if path.suffix.lower() == ".py" else "//"
    insertions: Dict[int, List[str]] = {}
    for f in findings:
        marker = (
            f"{comment} TODO(jev-migrate): decision-shaped LLM call "
            f"(score {f.detail.score:.2f}, {f.detail.verdict}) — see jev_maps.py"
        )
        insertions.setdefault(f.line, []).append(marker)

    new_lines: List[str] = []
    for i, line in enumerate(original, start=1):
        if i in insertions:
            new_lines.extend(insertions[i])
            new_lines.append("")
        new_lines.append(line)

    diff = difflib.unified_diff(
        original, new_lines, fromfile=f"a/{rel}", tofile=f"b/{rel}", lineterm=""
    )
    return "\n".join(diff)


def generate(scan: CodeScan, out_dir: Path, min_score: float = 0.60) -> MigrationOutput:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    sites = [f for f in scan.findings if f.detail.score >= min_score]
    maps = build_maps(
        [
            MapItem(
                prompt=f.prompt_excerpt,
                output="",
                score=f.detail.score,
                origin=f"{f.path}:{f.line}",
            )
            for f in sites
        ]
    )
    maps_py = _maps_py_source(maps, scan.root)
    migration_md = _migration_md(scan, maps, out_dir, min_score, applied=False)

    patch_parts: List[str] = []
    by_file: Dict[str, List[CodeFinding]] = {}
    for f in sites:
        by_file.setdefault(f.path, []).append(f)
    root = Path(scan.root)
    for rel in sorted(by_file):
        path = root / rel
        if not path.is_file():
            continue
        patch_parts.append(_patch_for_file(path, rel, by_file[rel], min_score))
    new_file_diff = "\n".join(
        difflib.unified_diff(
            [], maps_py.splitlines(), fromfile="/dev/null", tofile="b/jev_maps.py", lineterm=""
        )
    )
    patch_parts.append(new_file_diff)

    patch_path = out_dir / "migration.patch"
    patch_path.write_text("\n".join(p for p in patch_parts if p) + "\n", encoding="utf-8")

    maps_path = out_dir / "jev_maps.py"
    maps_path.write_text(maps_py, encoding="utf-8")
    md_path = out_dir / "MIGRATION.md"
    md_path.write_text(migration_md, encoding="utf-8")

    return MigrationOutput(
        out_dir=out_dir,
        files=[maps_path, md_path, patch_path],
        patch=patch_path,
        sites=len(sites),
        maps_n=len(maps),
    )


def apply_patch(patch: Path, root: Path) -> Tuple[bool, str]:
    """Apply a unified patch with git apply (no repo required)."""
    try:
        proc = subprocess.run(
            ["git", "apply", "--whitespace=nowarn", str(patch)],
            cwd=str(root), capture_output=True, text=True, timeout=60,
        )
    except FileNotFoundError:
        return False, "git not found on PATH"
    except subprocess.TimeoutExpired:
        return False, "git apply timed out"
    if proc.returncode != 0:
        return False, (proc.stderr or proc.stdout or "git apply failed").strip()
    return True, ""
